# Change these first
owner: FahmiBahtiar # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Blimbing Portofolio
    url: https://blimbing.xyz
  - name: Code Market
    url: https://codemarket.blimbing.xyz
  - name: Blog Blimbing
    url: https://blog.blimbing.xyz


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.blimbing.xyz
  # baseUrl: /deeper-upptime
  logoUrl: https://png.pngtree.com/png-clipart/20230823/original/pngtree-plane-logo-vector-template-picture-image_8258410.png
  name: Blimbing Service Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: blimbing.xyz
      href: https://blimbing.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
